const stories = [
    {
        id:1,
        image:"alok-kumar-sah.jpg",
        name:"alokkumax"
    },
    {
        id:2,
        image:"nandini-gupta.jpg",
        name:"nandini.oops"
    },
    {
        id:3,
        image:"allu-arjun.jpg",
        name:"alluarjunonline"
    },
    {
        id:4,
        image:"virat-kohli.jpg",
        name:"virat.kohli"
    },
    {
        id:5,
        image:"msdhoni.jpg",
        name:"mahi7781"
    },
    {
        id:6,
        image:"srk.jpg",
        name:"iamsrk"
    },
    {
        id:7,
        image:"deepika-padukone.jpg",
        name:"deepikapadukone"
    },
    {
        id:8,
        image:"chris-evans.jpg",
        name:"chrisevans"
    },
    {
        id:9,
        image:"katrina-kaif.jpg",
        name:"katrinakaif"
    },
    {
        id:10,
        image:"rohit-sharma.jpg",
        name:"rohitsharma45"
    },
]

export default stories;